# Generated by Django 4.2.28 on 2026-07-22 13:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_growth_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='xiaoyi', max_length=30)),
                ('external_conversation_id', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('last_interacted_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrowthPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=255)),
                ('starts_on', models.DateField(default=datetime.date.today)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('replaced', '已更新')], default='active', max_length=20)),
                ('rationale', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentUserBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='xiaoyi', max_length=30)),
                ('external_user_id', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('bound_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_bindings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentToolLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=80)),
                ('request_summary', models.JSONField(blank=True, default=dict)),
                ('result_status', models.CharField(choices=[('success', '成功'), ('error', '失败')], max_length=20)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tool_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'Agent'), ('tool', '工具')], max_length=20)),
                ('content_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.agentconversation')),
            ],
        ),
        migrations.CreateModel(
            name='AgentBindingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_digest', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_binding_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProactiveSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('trigger_reason', models.CharField(max_length=255)),
                ('scheduled_for', models.DateTimeField()),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proactive_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'scheduled_for', 'completed_at'], name='agent_suggestion_user_idx')],
            },
        ),
        migrations.CreateModel(
            name='GrowthTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('seven_days', '7天'), ('one_month', '1个月'), ('three_months', '3个月')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('action_type', models.CharField(blank=True, max_length=50)),
                ('resource_type', models.CharField(blank=True, max_length=30)),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '待完成'), ('completed', '已完成'), ('skipped', '已跳过')], default='pending', max_length=20)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.growthplan')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'indexes': [models.Index(fields=['plan', 'stage', 'status'], name='growth_task_plan_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='growthplan',
            index=models.Index(fields=['user', 'status', '-created_at'], name='growth_plan_user_idx'),
        ),
        migrations.AddIndex(
            model_name='agentuserbinding',
            index=models.Index(fields=['platform', 'external_user_id', 'is_active'], name='agent_binding_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentuserbinding',
            constraint=models.UniqueConstraint(fields=('platform', 'external_user_id'), name='unique_agent_external_id'),
        ),
        migrations.AddConstraint(
            model_name='agentuserbinding',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('platform', 'user'), name='unique_active_agent_user'),
        ),
        migrations.AddIndex(
            model_name='agenttoollog',
            index=models.Index(fields=['skill_name', '-created_at'], name='agent_tool_skill_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentconversation',
            constraint=models.UniqueConstraint(fields=('platform', 'external_conversation_id'), name='unique_agent_conversation'),
        ),
        migrations.AddIndex(
            model_name='agentbindingcode',
            index=models.Index(fields=['user', 'expires_at'], name='agent_code_user_exp_idx'),
        ),
    ]
