# Generated by Django 4.2.28 on 2026-07-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_agent_mvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuserbinding',
            name='access_token_digest',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
